import Head from "next/head";
import React, { ChangeEvent } from "react";
import type { NextPage } from "next";
import { useCart } from "../contexts/CartContext";
import { ItemRecipe } from "../components/custom/ItemRecipe";
import { useItemRecipe } from "../contexts/ItemContext";
import { SolidButton } from "../components/core/SolidButton";
import { AddItem } from "../components/core/AddItem";
import { Input } from "../components/core/Input";
import { CenterLayout } from "../layouts/CenterLayout";
import { Title } from "../components/core/Title";

const Home: NextPage = () => {
  const { items, selectedItem, selectItem } = useItemRecipe();
  const { totalPrice, addToCart } = useCart();

  return (
    <div>
      <Head>
        <title>New World | Calculadora de Craft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenterLayout>
        <Title>Calculadora de Craft</Title>

        <Input
          type="text"
          placeholder="Pesquisar..."
          className="rounded-md input-border  bg-theme-gray-400 focus:outline-0 text-white"
        />

        <div className="bg-theme-gray-200  rounded-md py-3 px-4 mt-10">
          <ItemRecipe item={selectedItem} />

          {/* <p>Preço total do craft: {totalPrice}</p> */}
          <div className="flex flex-wrap w-full">
            <AddItem></AddItem>
            <SolidButton onClick={() => addToCart(selectedItem)}>
              Adicionar
            </SolidButton>
          </div>
        </div>
      </CenterLayout>
    </div>
  );
};

export default Home;
